[build]
# Enable local-time feature
# See https://github.com/time-rs/time/issues/293#issuecomment-1005002386 
# and https://docs.rs/time/0.3.9/time/index.html#feature-flags.
rustflags = "--cfg unsound_local_offset"
