[sealer_rpc]
url = "ws://127.0.0.1:1789/rpc/v0"

[sealing]
enable_deals = false
max_retries = 3

[static_tree_d]
2KiB = "./tmp/2k/sc-02-data-tree-d.dat"

[[store]]
location = "./tmp/store1"

[[store]]
location = "./tmp/store2"

[[store]]
location = "./tmp/store3"

[limit]
pc1 = 3
pc2 = 2
c2 = 1

[remote]
path = "./tmp/remote"

[processors.tree_d]
external = true

[[processors.tree_d.subs]]

[processors.pc2]
external = true

[[processors.pc2.subs]]
# [processors.pc2.subs.cgroup]
# cpuset = "24-27"

[[processors.pc2.subs]]
[processors.pc2.subs.cgroup]
cpuset = "28-31"

[processors.c2]
external = true

[[processors.c2.subs]]
[processors.c2.subs.cgroup]
cpuset = "32-47"
