[rpc]
endpoint = "ws://127.0.0.1:1789/rpc/v0"

[sealing]
enable_deals = false
max_retries = 3

[[store]]
location = "./tmp/store1"

[limit]
pc1 = 1
pc2 = 1
c2 = 1

[remote]
path = "./tmp/remote"

[processors.pc2]
external = true

[processors.c2]
external = true

[processors.c2.cgroup]
cpuset = "24-47"
