[package]
name = "venus-worker"
version = "0.1.0"
authors = ["dtynn <dtynn@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
filecoin-proofs-api = "8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.56"
serde_repr = "0.1"
base64-serde = "0.6"
base64 = "0.13"
forest_json_utils = "0.1"
forest_address = "0.3"
forest_cid = "0.3"
fil_clock = "0.1"
crossbeam-channel = "0.5"
crossbeam-utils = "0.8.5"
tracing = "0.1"
tracing-subscriber = "0.2"
crossterm = "0.20"
jsonrpc-core = "17"
jsonrpc-derive = "17"
jsonrpc-ws-server = "17"
async-std = "1.9"
toml = "0.5"
humantime-serde = "1"
clap = "2.33"
byte-unit = "4"
cgroups-rs = "0.2"
signal-hook = "0.3"
flexi_logger = "0.18"
ansi_term = "0.12.1"

[dependencies.fil_types]
version = "0.2"
features = ["json"]

[dependencies.async-tungstenite]
version = "*"
features = ["async-native-tls"]

[dependencies.rocksdb]
version = "0.16"

[dependencies.jsonrpc-core-client]
version = "17.0"
path = "./jsonrpc-core-client"
