[package]
name = "venus-worker"
version = "0.1.0"
authors = ["dtynn <dtynn@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
filecoin-proofs-api = "8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.56"
forest_encoding = "0.2"
forest_json_utils = "0.1"
fil_clock = "0.1"
crossbeam-channel = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
crossterm = "0.20"
jsonrpc-core = "17"
jsonrpc-core-client = "17"
jsonrpc-derive = "17"

[dependencies.fil_types]
version = "0.2"
features = ["json"]
