[package]
name = "vc-processors"
version = "0.0.1"
edition = "2021"
license = "MIT"
keywords = [
    "filecoin",
    "venus",
    "venus-cluster",
    "venus-worker",
]
description = "provide core types & builtin processors for venus-worker"
homepage = "https://github.com/ipfs-force-community/venus-cluster"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
