# This is a basic workflow to help you get started with Actions
name: compile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  complie:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: dependencies
        run: sudo apt install mesa-opencl-icd ocl-icd-opencl-dev gcc git bzr jq pkg-config curl clang build-essential hwloc libhwloc-dev wget -y

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.52.1'

      - name: build venus-sector-manager
        run: make build-smgr

      - name: upload venuse-sector-manager
        uses: actions/upload-artifact@v2
        with:
          name: venus-sector-manager
          path: ./dist/bin/venus-sector-manager
          retention-days: 7
