# This is a basic workflow to help you get started with Actions
name: compile-go-on-pr

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main, release/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: dependencies
        run: sudo apt update && sudo apt install --reinstall ocl-icd-opencl-dev libhwloc-dev -y

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: build venus-sector-manager
        run: make build-smgr

      - name: show bins
        run: ls -lha ./dist/bin/


      # - name: upload venus-sector-manager
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: venus-sector-manager
      #     path: ./dist/bin/
      #     if-no-files-found: error
      #     retention-days: 3
