name: vc-processors-publish

on:
  push:
    tags: [vc-processors/v**]


jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.60.0'

      - name: dependencies
        run: sudo apt update && sudo apt install --reinstall ocl-icd-opencl-dev libhwloc-dev -y

      - name: cargo-publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_CRATES_IO_API_TOKEN }}
        run:
          make -C ./venus-worker/ publish-vc-processors
